version = 0.1
[default.global.parameters]
region = "us-east-1"

[staging.global.parameters]
region = "us-east-1"

[staging.deploy.parameters]
stack_name = "staging-todo-list-aws2"
#s3_bucket = "aws-sam-cli-managed-staging-samclisourcebucket-upt09go84tay"
#s3_prefix = "staging-todo-list-aws"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
resolve_s3 = true
confirm_changeset = true
